### PR TITLE
Ability to initialize RxMusicPlayerItem with prefetched metadata

### PR DESCRIPTION
**Pull request by perechnev**
My suggestion if to make users able to initialize `RxMusicPlayerItem` with prefetched metadata. Possibly you will also find it useful, like in case of my application.

Thank you @yoheimuta. Any feedback is welcome.

### CODE REVIEW

**Comment by yoheimuta** [comment]
@perechnev Thank you for your suggestion! That's helpful.
I'm going to tweak some before cutting the next release.

**Comment by yoheimuta** [comment]
> I'm going to tweak some 

- tweak: https://github.com/yoheimuta/RxMusicPlayer/compare/e4ce04c...cb0d39a
- I checked with the below diff that downloading a meta is successfully skipped.

```diff
diff --git a/Example/TableViewController.swift b/Example/TableViewController.swift
index 515c802..09027f2 100644
--- a/Example/TableViewController.swift
+++ b/Example/TableViewController.swift
@@ -6,6 +6,7 @@
 //  Copyright © 2019 YOSHIMUTA YOHEI. All rights reserved.
 //
 
+import AVFoundation
 import RxCocoa
 import RxMusicPlayer
 import RxSwift
@@ -39,7 +40,10 @@ class TableViewController: UITableViewController {
             "https://storage.googleapis.com/maison-great-dev/oss/musicplayer/tagmp3_4690995.mp3",
             "https://storage.googleapis.com/maison-great-dev/oss/musicplayer/tagmp3_9179181.mp3",
         ]
-        .map({ RxMusicPlayerItem(url: URL(string: $0)!) })
+        .map({ RxMusicPlayerItem(url: URL(string: $0)!,
+                                 meta: RxMusicPlayerItem.Meta(duration: CMTime(seconds: 60, preferredTimescale: 1),
+                                                              lyrics: "hoge", title: "title",
+                                                              album: "bbb", artist: "fuga", artwork: nil)) })
         let player = RxMusicPlayer(items: items)!
 
         // 2) Control views
```

**Comment by perechnev** [comment]
Great job, thank you @yoheimuta!

**Comment by yoheimuta** [comment]
I released v1.0.0 because this library is used by some production apps and ready.

**Pull request merged**
